const authors = [
  { name: "天义居士", image: "freecompress-于谆之.png", link: "于谆之" },
  { name: "莺本斋", image: "freecompress-莺本斋.png", link: "莺本斋" },
  { name: "玉书道人", image: "freecompress-玉书道人.png", link: "玉书道人" },
  { name: "无为", image: "freecompress-无为.png", link: "无为" },
  { name: "失堂", image: "freecompress-失堂.png", link: "失堂" },
  { name: "程岑", image: "freecompress-程岑.png", link: "程岑" },
  { name: "少璞", image: "freecompress-少璞.png", link: "少璞" },
  { name: "金风", image: "freecompress-金风.png", link: "金风" },
  { name: "高子琅", image: "freecompress-高子琅.png", link: "高子琅" },
  { name: "子平", image: "freecompress-子平.png", link: "子平" },
  { name: "何梦溪", image: "freecompress-何梦溪.png", link: "何梦溪" },
  { name: "谷旻灵", image: "freecompress-谷旻灵.png", link: "谷旻灵" },
  { name: "白昼", image: "freecompress-白昼.png", link: "白昼" },
  { name: "则好", image: "freecompress-则好.png", link: "则好" },
  { name: "桔子", image: "freecompress-桔子.png", link: "桔子" },
  { name: "摛翰", image: "freecompress-摛翰.png", link: "摛翰" },
  { name: "苏沐影", image: "freecompress-苏沐影.png", link: "苏沐影" },
  { name: "子远", image: "freecompress-子远.png", link: "子远" },
  { name: "李岚霏", image: "freecompress-李岚霏.png", link: "李岚霏" },
  { name: "于唐樾", image: "freecompress-于唐樾.png", link: "于唐樾" },
  { name: "扈江离", image: "小型-扈江离.png", link: "扈江离" },
  { name: "江南", image: "小型-江南.png", link: "江南" },
  { name: "灼夭", image: "小型-灼夭.png", link: "灼夭" },
  { name: "临界", image: "小型-临界.png", link: "临界" },
];
